GO_EASY_ON_ME = 1
ARCHS = armv7
include ../theos/makefiles/common.mk

LIBRARY_NAME = InjectionAW
InjectionAW_FILES = Injection.c
InjectionAW_FRAMEWORKS = CoreFoundation
InjectionAW_LIBRARIES = MobileGestalt

include $(THEOS_MAKE_PATH)/library.mk
